version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./php/src:/var/www/html
     - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
     - php
    networks:
     - net
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
     - database
     - redis
    volumes:
     - ./php/src/:/var/www/html/
    ports:
     - 8000:80
    networks:
     - net
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
     MYSQL_DATABASE: MYSQL_DATABASE
     MYSQL_USER: MYSQL_USER
     MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
     - "9906:3306"
    volumes:
     - my-data:/var/lib/mysql
    networks:
     - net
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports: 
     - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass REDIS_PASSWORD
    volumes: 
     - my-data:/data
    networks:
     - net
volumes:
  my-data:

networks:
  net:
    driver: "bridge"